spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/lemon

  docker:
    compose:
      enabled: true
      file: "./docker-compose.yml"
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: toyProject
